<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pegawai extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pegawai_model');
    } 

    /*
     * Listing of pegawai
     */
    function index()
    {
        $data['title'] = "List Pegawai";

        $data['listt'] = $this->Pegawai_model->get_all_pegawai();
        $data['page'] = 'indexx';   
        $this->renderDokter($data);
    }
          public function renderDokter($data){
      $this->load->view('partial/header.php');
      $this->load->view('partial/mainDashboard',$data);
      $this->load->view('partial/footer.php');
    }

    /*
     * Adding a new pegawai
     */
    function add()
    {   

        $data['title'] = "Add Pegawai";
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'jk' => $this->input->post('jk'),
				'kd_pegawai' => $this->input->post('kd_pegawai'),
				'nm_pegawai' => $this->input->post('nm_pegawai'),
				'tmp_lahir' => $this->input->post('tmp_lahir'),
				'tgl_lahir' => $this->input->post('tgl_lahir'),
				'gol_drh' => $this->input->post('gol_drh'),
				'agama' => $this->input->post('agama'),
                );
            
            $pegawai_id = $this->Pegawai_model->add_pegawai($params);
            redirect('pegawai/index');
        }
        else
        {            
        $data['page'] = 'addpegawai';   
        $this->renderDokter($data);
        }
    }  

    /*
     * Editing a pegawai
     */
    function edit($id_pegawai)
    {   

        $data['title'] = "Edit Pegawai";
        // check if the pegawai exists before trying to edit it
        $data['pegawai'] = $this->Pegawai_model->get_pegawai($id_pegawai);
        
        if(isset($data['pegawai']['id_pegawai']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'jk' => $this->input->post('jk'),
					'tmp_lahir' => $this->input->post('tmp_lahir'),
					'tgl_lahir' => $this->input->post('tgl_lahir'),
					'gol_drh' => $this->input->post('gol_drh'),
					'agama' => $this->input->post('agama'),
					'kd_pegawai' => $this->input->post('kd_pegawai'),
					'nm_pegawai' => $this->input->post('nm_pegawai'),
                );

                $this->Pegawai_model->update_pegawai($id_pegawai,$params);            
                redirect('pegawai/index');
            }
            else
            {
        $data['page'] = 'editpegawai';   
        $this->renderDokter($data);
            }
        }
        else
            show_error('The pegawai you are trying to edit does not exist.');
    } 

    /*
     * Deleting pegawai
     */
    function remove($id_pegawai)
    {
        $pegawai = $this->Pegawai_model->get_pegawai($id_pegawai);

        // check if the pegawai exists before trying to delete it
        if(isset($pegawai['id_pegawai']))
        {
            $this->Pegawai_model->delete_pegawai($id_pegawai);
            redirect('pegawai/index');
        }
        else
            show_error('The pegawai you are trying to delete does not exist.');
    }
    
}
